### ISSUE TITLE
KITTI depth image

### ISSUE THREAD

**Issue by ZXia221** [shiyujiao/HighlyAccurate#1]
Hi Yujiao,

Thank you so much for sharing the code of your paper. I have your satellite images and KITTI raw data downloaded and was trying to run your code. However, the code complains that it cannot find the depth image.

The error message I got:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/zxia/staff_bulk_mounted/datasets/KITTI/depth/data_depth_annotated/train/2011_09_26_drive_0061_sync/proj_depth/groundtruth/image_02/0000000403.png'

In ./dataLoader/KITTI line 161, you called the "depth_read" function, and seems it tries to read some depth images. According to the Readme and paper, I understood that no depth image is needed. I wonder do I need to download depth data from KITTI as well? If so, could you please provide more details on that?

Thank you and looking forward to your reply.

Best regards,
Zimin

**Comment by ZXia221** [comment]
I think I figured this out. Seems the depth maps from KITTI are also needed for running the code. I guess it would be very helpful if you can add this to readme as well.

Best regards,
Zimin

**Comment by Miaowshroom** [comment]
> 

@ZXia221 I also run into this problem, but you can modify the code to train and test without using the depth image. I believe in the paper the results are trained without depth information.

**Comment by shiyujiao** [comment]
> > 
> 
> @ZXia221 I also run into this problem, but you can modify the code to train and test without using the depth image. I believe in the paper the results are trained without depth information.

Hi, I have updated the code. Could you please try again and let me know if there are still problems?

**Comment by shiyujiao** [comment]
> I think I figured this out. Seems the depth maps from KITTI are also needed for running the code. I guess it would be very helpful if you can add this to readme as well.
> 
> Best regards, Zimin

Thank you, Zimin!

**Comment by Miaowshroom** [comment]
> > I think I figured this out. Seems the depth maps from KITTI are also needed for running the code. I guess it would be very helpful if you can add this to readme as well.
> > Best regards, Zimin
> 
> Thank you, Zimin!

Hi Dr Shi, 
For the new commit, some comments:

1. I think you accidentally removed `self.file_name = [file[:-1] for file in file_name]` and `grd_left_imgs = torch.cat([grd_left_imgs, grd_img_left.unsqueeze(0)], dim=0)` in KITTI_dataset.py
2. Also need to remove the arg `gt_depth=gt_depth` in line 358 in train_kitti.py

**Comment by shiyujiao** [comment]
> 

Updated. Thanks a lot!

**Comment by ZXia221** [comment]
I see. Thank you both!
