### ISSUE TITLE
Link to trained model expired

### ISSUE THREAD

**Issue by LukeBriggsDev** [shiyujiao/HighlyAccurate#5]
The [link to the trained model](https://anu365-my.sharepoint.com/:f:/g/personal/u6293587_anu_edu_au/Ev7HAgSDze5LhvRWfcM4AgEBJiSr6W0GuTEEfdhWHG_gSQ?e=vNtwCJ) has expired, could a new link be made?

thanks.

**Comment by shiyujiao** [comment]
Thanks for reporting this. I have updated the expiry date.
